# Cloudflare Workers configuration for Product Description Generator

name = "product-description-generator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"

# Production environment
[env.production]
name = "product-description-generator"

# Staging environment for testing
[env.staging]
name = "product-description-generator-staging"

